export interface EmojiEntry {
  emoji: string;
  name: string;
  category: string;
}

// A curated, hand-picked set rather than the full Unicode emoji database —
// enough breadth for real day-to-day chat use without shipping/maintaining
// an exhaustive (and much larger) emoji package.
export const EMOJI_LIST: EmojiEntry[] = [
  // Smileys
  { emoji: "😀", name: "grinning", category: "Smileys" },
  { emoji: "😃", name: "smiley", category: "Smileys" },
  { emoji: "😄", name: "smile", category: "Smileys" },
  { emoji: "😁", name: "grin", category: "Smileys" },
  { emoji: "😆", name: "laughing", category: "Smileys" },
  { emoji: "😅", name: "sweat smile", category: "Smileys" },
  { emoji: "🤣", name: "rofl", category: "Smileys" },
  { emoji: "😂", name: "joy tears", category: "Smileys" },
  { emoji: "🙂", name: "slightly smiling", category: "Smileys" },
  { emoji: "🙃", name: "upside down", category: "Smileys" },
  { emoji: "😉", name: "wink", category: "Smileys" },
  { emoji: "😊", name: "blush", category: "Smileys" },
  { emoji: "😇", name: "innocent halo", category: "Smileys" },
  { emoji: "🥰", name: "smiling hearts", category: "Smileys" },
  { emoji: "😍", name: "heart eyes", category: "Smileys" },
  { emoji: "🤩", name: "star struck", category: "Smileys" },
  { emoji: "😘", name: "kiss heart", category: "Smileys" },
  { emoji: "😗", name: "kissing", category: "Smileys" },
  { emoji: "😋", name: "yum", category: "Smileys" },
  { emoji: "😛", name: "tongue", category: "Smileys" },
  { emoji: "😜", name: "wink tongue", category: "Smileys" },
  { emoji: "🤪", name: "zany crazy", category: "Smileys" },
  { emoji: "😝", name: "squint tongue", category: "Smileys" },
  { emoji: "🤑", name: "money mouth", category: "Smileys" },
  { emoji: "🤗", name: "hugging", category: "Smileys" },
  { emoji: "🤭", name: "hand over mouth", category: "Smileys" },
  { emoji: "🤫", name: "shush quiet", category: "Smileys" },
  { emoji: "🤔", name: "thinking", category: "Smileys" },
  { emoji: "🤐", name: "zipper mouth", category: "Smileys" },
  { emoji: "🙄", name: "eye roll", category: "Smileys" },
  { emoji: "😏", name: "smirk", category: "Smileys" },
  { emoji: "😣", name: "persevere", category: "Smileys" },
  { emoji: "😥", name: "sad relieved", category: "Smileys" },
  { emoji: "😮", name: "open mouth", category: "Smileys" },
  { emoji: "🤐", name: "silent", category: "Smileys" },
  { emoji: "😯", name: "hushed", category: "Smileys" },
  { emoji: "😪", name: "sleepy", category: "Smileys" },
  { emoji: "😫", name: "tired", category: "Smileys" },
  { emoji: "🥱", name: "yawn", category: "Smileys" },
  { emoji: "😴", name: "sleeping zzz", category: "Smileys" },
  { emoji: "😌", name: "relieved", category: "Smileys" },
  { emoji: "😛", name: "sticking tongue", category: "Smileys" },
  { emoji: "😷", name: "mask sick", category: "Smileys" },
  { emoji: "🤒", name: "thermometer sick", category: "Smileys" },
  { emoji: "🤕", name: "bandage hurt", category: "Smileys" },
  { emoji: "🤢", name: "nauseated", category: "Smileys" },
  { emoji: "🤮", name: "vomit", category: "Smileys" },
  { emoji: "🤧", name: "sneeze", category: "Smileys" },
  { emoji: "🥵", name: "hot sweat", category: "Smileys" },
  { emoji: "🥶", name: "cold freezing", category: "Smileys" },
  { emoji: "🥴", name: "woozy", category: "Smileys" },
  { emoji: "😵", name: "dizzy", category: "Smileys" },
  { emoji: "🤯", name: "mind blown", category: "Smileys" },
  { emoji: "🤠", name: "cowboy", category: "Smileys" },
  { emoji: "🥳", name: "party celebrate", category: "Smileys" },
  { emoji: "🥸", name: "disguise", category: "Smileys" },
  { emoji: "😎", name: "sunglasses cool", category: "Smileys" },
  { emoji: "🤓", name: "nerd glasses", category: "Smileys" },
  { emoji: "🧐", name: "monocle", category: "Smileys" },
  { emoji: "😕", name: "confused", category: "Smileys" },
  { emoji: "😟", name: "worried", category: "Smileys" },
  { emoji: "🙁", name: "slight frown", category: "Smileys" },
  { emoji: "😮‍💨", name: "exhale", category: "Smileys" },
  { emoji: "😨", name: "fearful", category: "Smileys" },
  { emoji: "😰", name: "anxious sweat", category: "Smileys" },
  { emoji: "😥", name: "sad", category: "Smileys" },
  { emoji: "😢", name: "cry", category: "Smileys" },
  { emoji: "😭", name: "sob crying", category: "Smileys" },
  { emoji: "😱", name: "scream", category: "Smileys" },
  { emoji: "😖", name: "confounded", category: "Smileys" },
  { emoji: "😣", name: "struggling", category: "Smileys" },
  { emoji: "😞", name: "disappointed", category: "Smileys" },
  { emoji: "😓", name: "downcast sweat", category: "Smileys" },
  { emoji: "😩", name: "weary", category: "Smileys" },
  { emoji: "😫", name: "exhausted", category: "Smileys" },
  { emoji: "🥺", name: "pleading puppy eyes", category: "Smileys" },
  { emoji: "😡", name: "angry mad", category: "Smileys" },
  { emoji: "😠", name: "annoyed", category: "Smileys" },
  { emoji: "🤬", name: "cursing swearing", category: "Smileys" },
  { emoji: "😈", name: "devil smiling", category: "Smileys" },
  { emoji: "👿", name: "devil angry", category: "Smileys" },
  { emoji: "💀", name: "skull dead", category: "Smileys" },
  { emoji: "☠️", name: "skull crossbones", category: "Smileys" },
  { emoji: "💩", name: "poop", category: "Smileys" },
  { emoji: "🤡", name: "clown", category: "Smileys" },
  { emoji: "👹", name: "ogre", category: "Smileys" },
  { emoji: "👻", name: "ghost", category: "Smileys" },
  { emoji: "👽", name: "alien", category: "Smileys" },
  { emoji: "🤖", name: "robot", category: "Smileys" },

  // Gestures / People
  { emoji: "👋", name: "wave hello", category: "Gestures" },
  { emoji: "🤚", name: "raised back hand", category: "Gestures" },
  { emoji: "✋", name: "raised hand stop", category: "Gestures" },
  { emoji: "🖖", name: "vulcan salute", category: "Gestures" },
  { emoji: "👌", name: "ok hand", category: "Gestures" },
  { emoji: "🤌", name: "pinched fingers", category: "Gestures" },
  { emoji: "✌️", name: "peace victory", category: "Gestures" },
  { emoji: "🤞", name: "fingers crossed", category: "Gestures" },
  { emoji: "🤟", name: "love you gesture", category: "Gestures" },
  { emoji: "🤘", name: "rock on horns", category: "Gestures" },
  { emoji: "👈", name: "point left", category: "Gestures" },
  { emoji: "👉", name: "point right", category: "Gestures" },
  { emoji: "👆", name: "point up", category: "Gestures" },
  { emoji: "👇", name: "point down", category: "Gestures" },
  { emoji: "👍", name: "thumbs up", category: "Gestures" },
  { emoji: "👎", name: "thumbs down", category: "Gestures" },
  { emoji: "✊", name: "fist raised", category: "Gestures" },
  { emoji: "👊", name: "fist bump punch", category: "Gestures" },
  { emoji: "🤛", name: "fist left", category: "Gestures" },
  { emoji: "🤜", name: "fist right", category: "Gestures" },
  { emoji: "👏", name: "clap applause", category: "Gestures" },
  { emoji: "🙌", name: "raise hands celebrate", category: "Gestures" },
  { emoji: "👐", name: "open hands", category: "Gestures" },
  { emoji: "🤲", name: "palms up", category: "Gestures" },
  { emoji: "🙏", name: "pray thanks please", category: "Gestures" },
  { emoji: "🤝", name: "handshake deal", category: "Gestures" },
  { emoji: "💪", name: "flex muscle strong", category: "Gestures" },
  { emoji: "🫡", name: "salute", category: "Gestures" },
  { emoji: "🫠", name: "melting", category: "Gestures" },
  { emoji: "🫣", name: "peeking eyes", category: "Gestures" },
  { emoji: "🫥", name: "dotted face", category: "Gestures" },

  // Hearts / Symbols
  { emoji: "❤️", name: "red heart love", category: "Symbols" },
  { emoji: "🧡", name: "orange heart", category: "Symbols" },
  { emoji: "💛", name: "yellow heart", category: "Symbols" },
  { emoji: "💚", name: "green heart", category: "Symbols" },
  { emoji: "💙", name: "blue heart", category: "Symbols" },
  { emoji: "💜", name: "purple heart", category: "Symbols" },
  { emoji: "🖤", name: "black heart", category: "Symbols" },
  { emoji: "🤍", name: "white heart", category: "Symbols" },
  { emoji: "🤎", name: "brown heart", category: "Symbols" },
  { emoji: "💔", name: "broken heart", category: "Symbols" },
  { emoji: "❣️", name: "heart exclamation", category: "Symbols" },
  { emoji: "💕", name: "two hearts", category: "Symbols" },
  { emoji: "💞", name: "revolving hearts", category: "Symbols" },
  { emoji: "💓", name: "beating heart", category: "Symbols" },
  { emoji: "💗", name: "growing heart", category: "Symbols" },
  { emoji: "💖", name: "sparkling heart", category: "Symbols" },
  { emoji: "💘", name: "heart arrow cupid", category: "Symbols" },
  { emoji: "💝", name: "heart gift", category: "Symbols" },
  { emoji: "💯", name: "hundred perfect", category: "Symbols" },
  { emoji: "🔥", name: "fire lit", category: "Symbols" },
  { emoji: "✨", name: "sparkles", category: "Symbols" },
  { emoji: "🎉", name: "party popper tada", category: "Symbols" },
  { emoji: "🎊", name: "confetti ball", category: "Symbols" },
  { emoji: "💥", name: "boom explosion", category: "Symbols" },
  { emoji: "💫", name: "dizzy stars", category: "Symbols" },
  { emoji: "💦", name: "sweat droplets", category: "Symbols" },
  { emoji: "💨", name: "dash zoom", category: "Symbols" },
  { emoji: "🕳️", name: "hole", category: "Symbols" },
  { emoji: "💬", name: "speech bubble", category: "Symbols" },
  { emoji: "💭", name: "thought bubble", category: "Symbols" },
  { emoji: "✅", name: "check mark", category: "Symbols" },
  { emoji: "❌", name: "cross x no", category: "Symbols" },
  { emoji: "❓", name: "question mark", category: "Symbols" },
  { emoji: "❗", name: "exclamation mark", category: "Symbols" },
  { emoji: "⚠️", name: "warning", category: "Symbols" },
  { emoji: "🚫", name: "prohibited no entry", category: "Symbols" },
  { emoji: "♻️", name: "recycle", category: "Symbols" },
  { emoji: "⭐", name: "star", category: "Symbols" },
  { emoji: "🌟", name: "glowing star", category: "Symbols" },
  { emoji: "🆗", name: "ok button", category: "Symbols" },
  { emoji: "🆒", name: "cool button", category: "Symbols" },
  { emoji: "🔞", name: "18 plus", category: "Symbols" },

  // Animals
  { emoji: "🐶", name: "dog", category: "Animals" },
  { emoji: "🐱", name: "cat", category: "Animals" },
  { emoji: "🐭", name: "mouse", category: "Animals" },
  { emoji: "🐹", name: "hamster", category: "Animals" },
  { emoji: "🐰", name: "rabbit bunny", category: "Animals" },
  { emoji: "🦊", name: "fox", category: "Animals" },
  { emoji: "🐻", name: "bear", category: "Animals" },
  { emoji: "🐼", name: "panda", category: "Animals" },
  { emoji: "🐨", name: "koala", category: "Animals" },
  { emoji: "🐯", name: "tiger", category: "Animals" },
  { emoji: "🦁", name: "lion", category: "Animals" },
  { emoji: "🐮", name: "cow", category: "Animals" },
  { emoji: "🐷", name: "pig", category: "Animals" },
  { emoji: "🐸", name: "frog", category: "Animals" },
  { emoji: "🐵", name: "monkey", category: "Animals" },
  { emoji: "🐔", name: "chicken", category: "Animals" },
  { emoji: "🐧", name: "penguin", category: "Animals" },
  { emoji: "🐦", name: "bird", category: "Animals" },
  { emoji: "🦆", name: "duck", category: "Animals" },
  { emoji: "🦅", name: "eagle", category: "Animals" },
  { emoji: "🦉", name: "owl", category: "Animals" },
  { emoji: "🦇", name: "bat", category: "Animals" },
  { emoji: "🐺", name: "wolf", category: "Animals" },
  { emoji: "🐗", name: "boar", category: "Animals" },
  { emoji: "🐴", name: "horse", category: "Animals" },
  { emoji: "🦄", name: "unicorn", category: "Animals" },
  { emoji: "🐝", name: "bee", category: "Animals" },
  { emoji: "🐛", name: "bug caterpillar", category: "Animals" },
  { emoji: "🦋", name: "butterfly", category: "Animals" },
  { emoji: "🐌", name: "snail", category: "Animals" },
  { emoji: "🐞", name: "ladybug", category: "Animals" },
  { emoji: "🐜", name: "ant", category: "Animals" },
  { emoji: "🕷️", name: "spider", category: "Animals" },
  { emoji: "🦂", name: "scorpion", category: "Animals" },
  { emoji: "🐢", name: "turtle", category: "Animals" },
  { emoji: "🐍", name: "snake", category: "Animals" },
  { emoji: "🦎", name: "lizard", category: "Animals" },
  { emoji: "🐙", name: "octopus", category: "Animals" },
  { emoji: "🦑", name: "squid", category: "Animals" },
  { emoji: "🦀", name: "crab", category: "Animals" },
  { emoji: "🐠", name: "fish tropical", category: "Animals" },
  { emoji: "🐬", name: "dolphin", category: "Animals" },
  { emoji: "🐳", name: "whale", category: "Animals" },
  { emoji: "🦈", name: "shark", category: "Animals" },

  // Food
  { emoji: "🍏", name: "green apple", category: "Food" },
  { emoji: "🍎", name: "red apple", category: "Food" },
  { emoji: "🍌", name: "banana", category: "Food" },
  { emoji: "🍇", name: "grapes", category: "Food" },
  { emoji: "🍓", name: "strawberry", category: "Food" },
  { emoji: "🍒", name: "cherries", category: "Food" },
  { emoji: "🍑", name: "peach", category: "Food" },
  { emoji: "🍍", name: "pineapple", category: "Food" },
  { emoji: "🥝", name: "kiwi", category: "Food" },
  { emoji: "🍅", name: "tomato", category: "Food" },
  { emoji: "🥑", name: "avocado", category: "Food" },
  { emoji: "🍆", name: "eggplant", category: "Food" },
  { emoji: "🌽", name: "corn", category: "Food" },
  { emoji: "🥕", name: "carrot", category: "Food" },
  { emoji: "🥔", name: "potato", category: "Food" },
  { emoji: "🍞", name: "bread", category: "Food" },
  { emoji: "🥐", name: "croissant", category: "Food" },
  { emoji: "🧀", name: "cheese", category: "Food" },
  { emoji: "🍳", name: "fried egg", category: "Food" },
  { emoji: "🥓", name: "bacon", category: "Food" },
  { emoji: "🍔", name: "burger", category: "Food" },
  { emoji: "🍟", name: "fries", category: "Food" },
  { emoji: "🍕", name: "pizza", category: "Food" },
  { emoji: "🌭", name: "hot dog", category: "Food" },
  { emoji: "🌮", name: "taco", category: "Food" },
  { emoji: "🌯", name: "burrito", category: "Food" },
  { emoji: "🍝", name: "spaghetti pasta", category: "Food" },
  { emoji: "🍜", name: "ramen noodles", category: "Food" },
  { emoji: "🍣", name: "sushi", category: "Food" },
  { emoji: "🍱", name: "bento box", category: "Food" },
  { emoji: "🍦", name: "soft serve ice cream", category: "Food" },
  { emoji: "🍩", name: "donut", category: "Food" },
  { emoji: "🍪", name: "cookie", category: "Food" },
  { emoji: "🎂", name: "birthday cake", category: "Food" },
  { emoji: "🍰", name: "cake slice", category: "Food" },
  { emoji: "🧁", name: "cupcake", category: "Food" },
  { emoji: "🍫", name: "chocolate", category: "Food" },
  { emoji: "🍿", name: "popcorn", category: "Food" },
  { emoji: "☕", name: "coffee", category: "Food" },
  { emoji: "🍵", name: "tea", category: "Food" },
  { emoji: "🍺", name: "beer", category: "Food" },
  { emoji: "🍻", name: "beer cheers", category: "Food" },
  { emoji: "🍷", name: "wine", category: "Food" },
  { emoji: "🥂", name: "champagne toast", category: "Food" },
  { emoji: "🥃", name: "whiskey", category: "Food" },
  { emoji: "🍹", name: "cocktail tropical", category: "Food" },

  // Activities / Travel
  { emoji: "⚽", name: "soccer ball", category: "Activities" },
  { emoji: "🏀", name: "basketball", category: "Activities" },
  { emoji: "🏈", name: "football american", category: "Activities" },
  { emoji: "⚾", name: "baseball", category: "Activities" },
  { emoji: "🎾", name: "tennis", category: "Activities" },
  { emoji: "🏐", name: "volleyball", category: "Activities" },
  { emoji: "🎱", name: "8 ball pool", category: "Activities" },
  { emoji: "🏓", name: "ping pong", category: "Activities" },
  { emoji: "🎮", name: "video game controller", category: "Activities" },
  { emoji: "🕹️", name: "joystick arcade", category: "Activities" },
  { emoji: "🎲", name: "dice", category: "Activities" },
  { emoji: "🧩", name: "puzzle piece", category: "Activities" },
  { emoji: "🎯", name: "dart bullseye target", category: "Activities" },
  { emoji: "🎳", name: "bowling", category: "Activities" },
  { emoji: "🎸", name: "guitar", category: "Activities" },
  { emoji: "🎧", name: "headphones music", category: "Activities" },
  { emoji: "🎤", name: "microphone singing", category: "Activities" },
  { emoji: "🎬", name: "clapper film movie", category: "Activities" },
  { emoji: "🏆", name: "trophy win", category: "Activities" },
  { emoji: "🥇", name: "gold medal first", category: "Activities" },
  { emoji: "🚗", name: "car", category: "Activities" },
  { emoji: "🚕", name: "taxi", category: "Activities" },
  { emoji: "🚀", name: "rocket launch", category: "Activities" },
  { emoji: "✈️", name: "airplane flight", category: "Activities" },
  { emoji: "🚁", name: "helicopter", category: "Activities" },
  { emoji: "⛵", name: "sailboat", category: "Activities" },
  { emoji: "🏝️", name: "island beach", category: "Activities" },
  { emoji: "🏔️", name: "mountain", category: "Activities" },
  { emoji: "🎡", name: "ferris wheel", category: "Activities" },
  { emoji: "🎢", name: "roller coaster", category: "Activities" },

  // Objects
  { emoji: "💻", name: "laptop computer", category: "Objects" },
  { emoji: "🖥️", name: "desktop computer", category: "Objects" },
  { emoji: "⌨️", name: "keyboard", category: "Objects" },
  { emoji: "🖱️", name: "computer mouse", category: "Objects" },
  { emoji: "📱", name: "phone mobile", category: "Objects" },
  { emoji: "☎️", name: "telephone", category: "Objects" },
  { emoji: "📷", name: "camera", category: "Objects" },
  { emoji: "📹", name: "video camera", category: "Objects" },
  { emoji: "🔋", name: "battery", category: "Objects" },
  { emoji: "🔌", name: "plug electric", category: "Objects" },
  { emoji: "💡", name: "light bulb idea", category: "Objects" },
  { emoji: "🔦", name: "flashlight", category: "Objects" },
  { emoji: "🕯️", name: "candle", category: "Objects" },
  { emoji: "📚", name: "books", category: "Objects" },
  { emoji: "📖", name: "open book", category: "Objects" },
  { emoji: "✏️", name: "pencil", category: "Objects" },
  { emoji: "🖊️", name: "pen", category: "Objects" },
  { emoji: "📝", name: "memo notes", category: "Objects" },
  { emoji: "📌", name: "pushpin", category: "Objects" },
  { emoji: "📎", name: "paperclip attachment", category: "Objects" },
  { emoji: "🔒", name: "locked", category: "Objects" },
  { emoji: "🔓", name: "unlocked", category: "Objects" },
  { emoji: "🔑", name: "key", category: "Objects" },
  { emoji: "🔨", name: "hammer tool", category: "Objects" },
  { emoji: "🛠️", name: "hammer wrench tools", category: "Objects" },
  { emoji: "⚙️", name: "gear settings", category: "Objects" },
  { emoji: "🧰", name: "toolbox", category: "Objects" },
  { emoji: "🔍", name: "magnifying glass search", category: "Objects" },
  { emoji: "💰", name: "money bag", category: "Objects" },
  { emoji: "💳", name: "credit card", category: "Objects" },
  { emoji: "🎁", name: "gift present", category: "Objects" },
  { emoji: "🔔", name: "bell notification", category: "Objects" },
  { emoji: "🔕", name: "bell muted", category: "Objects" },
];

export const EMOJI_CATEGORIES = Array.from(new Set(EMOJI_LIST.map((e) => e.category)));
